import { readFile, writeFile } from 'fs/promises';
import { readFileSync } from 'fs';
import { joinDisplayPath, type ManagedProjectContextDisplayPaths } from './agent-context-paths.js';
import { STOP_HOOK_MIGRATION_BULLETS } from './stop-hook-guidance.js';

/**
 * Current template version. Increment when templates change.
 * Used for auto-upgrade on project switch.
 */
export const CURRENT_TEMPLATE_VERSION = 14;

/** Version marker format in generated files */
const VERSION_MARKER = `<!-- agenticos-template: v${CURRENT_TEMPLATE_VERSION} -->`;

const DEFAULT_AGENT_CONTEXT_PATHS: ManagedProjectContextDisplayPaths = {
  quickStartPath: '.context/quick-start.md',
  statePath: '.context/state.yaml',
  conversationsDir: '.context/conversations/',
  markerPath: '.context/.last_record',
  knowledgeDir: 'knowledge/',
  tasksDir: 'tasks/',
  artifactsDir: 'artifacts/',
};

function normalizeAgentContextPaths(paths?: Partial<ManagedProjectContextDisplayPaths>): ManagedProjectContextDisplayPaths {
  return {
    quickStartPath: paths?.quickStartPath || DEFAULT_AGENT_CONTEXT_PATHS.quickStartPath,
    statePath: paths?.statePath || DEFAULT_AGENT_CONTEXT_PATHS.statePath,
    conversationsDir: paths?.conversationsDir || DEFAULT_AGENT_CONTEXT_PATHS.conversationsDir,
    markerPath: paths?.markerPath || DEFAULT_AGENT_CONTEXT_PATHS.markerPath,
    knowledgeDir: paths?.knowledgeDir || DEFAULT_AGENT_CONTEXT_PATHS.knowledgeDir,
    tasksDir: paths?.tasksDir || DEFAULT_AGENT_CONTEXT_PATHS.tasksDir,
    artifactsDir: paths?.artifactsDir || DEFAULT_AGENT_CONTEXT_PATHS.artifactsDir,
  };
}

export const SHARED_POLICY_TITLE = 'Canonical Policy (Shared Across Agents)';
export const SHARED_POLICY_BULLETS = [
  'This project has one canonical AgenticOS execution policy across Claude Code, Codex, and other supported agents.',
  'Implementation work must stay issue-first, preflighted, and inside the guardrail-controlled branch/worktree flow.',
  'PR creation or merge must not happen before executable scope validation passes.',
  'Recording and save flow remain canonical project requirements rather than runtime-specific preferences.',
] as const;

export const AGENTS_ADAPTER_LINES = [
  '`AGENTS.md` is the Codex/generic adapter surface for this project.',
  'It must expose the same canonical policy as other agent adapters rather than defining a different workflow.',
] as const;

export const AGENTS_RUNTIME_GUIDANCE_TITLE = 'Codex / Generic Runtime Notes';
export const AGENTS_RUNTIME_GUIDANCE_BULLETS = [
  'If natural-language routing is weak, use explicit `agenticos_*` tool calls before treating the issue as transport failure.',
  'Bootstrap differences are runtime concerns rather than policy changes.',
  ...STOP_HOOK_MIGRATION_BULLETS,
] as const;

export const CLAUDE_ADAPTER_LINES = [
  '`CLAUDE.md` is the Claude Code adapter surface for this project.',
  'It must expose the same canonical policy as other agent adapters while allowing Claude-specific operator guidance.',
] as const;

export const CLAUDE_RUNTIME_GUIDANCE_TITLE = 'Claude Runtime Notes';
export const CLAUDE_RUNTIME_GUIDANCE_BULLETS = [
  'Claude CLI-managed user MCP config is the canonical Claude bootstrap surface.',
  'Claude-specific stop hooks remain optional local stop-hook reminders rather than canonical guardrails.',
  ...STOP_HOOK_MIGRATION_BULLETS,
] as const;

export const TASK_INTAKE_RULE_TITLE = 'Task Intake Rule';
export const TASK_INTAKE_RULE_CONTENT = `**Before writing any code or plan, verify three things:**

1. **Intent**: What is the operator actually trying to achieve? (Not what they said — what they mean)
2. **Data Source**: What source should I trust? Do not assume; verify.
3. **Scope**: Can this be done in one session? If not, where are the checkpoints?

If any of these cannot be answered clearly, **stop and ask**. Do not proceed with fuzzy assumptions.

Once intent is resolved, collapse it into a clean execution objective. Do not carry the full intake rubric through every later step.` as const;

export const DESIGN_PHILOSOPHY_TITLE = 'Design Philosophy';

/**
 * Design Philosophy is NOT generated by default.
 * It's only retained when upgrading an existing file that already contains it.
 * This is intentional: downstream projects don't need AgenticOS design rationale.
 * Only the canonical AgenticOS project retains Design Philosophy.
 */

export const CONTINUITY_CONTRACT_TITLE = 'Continuity Contract';
export const CONTINUITY_CONTRACT_BULLETS = [
  'The tracked continuity contract is publication-policy aware: local_private stays runtime-local, private_continuity persists the tracked continuity core, and public_distilled keeps a narrower tracked surface.',
  'The configured conversations path is a context contract input, but raw transcript routing may differ by publication policy.',
  '`CLAUDE.md` and `AGENTS.md` are mirrored adapter surfaces. They should stay aligned with project policy, but continuity correctness must not depend on them existing.',
] as const;

/** Extract template version from an existing file. Returns 0 if no marker found (v1 or earlier). */
export function extractTemplateVersion(content: string): number {
  const match = content.match(/<!--\s*agenticos-template:\s*v(\d+)\s*-->/);
  return match ? parseInt(match[1], 10) : 0;
}

/** Update version marker in existing content to current version */
function ensureVersionMarker(content: string): string {
  if (content.includes(`agenticos-template: v${CURRENT_TEMPLATE_VERSION}`)) return content;
  const cleaned = content.replace(/<!--\s*agenticos-template:\s*v\d+\s*-->\n?/, '');
  return `${VERSION_MARKER}\n${cleaned}`;
}

function renderSharedPolicySection(): string {
  return [
    `## ${SHARED_POLICY_TITLE}`,
    '',
    ...SHARED_POLICY_BULLETS.map((line) => `- ${line}`),
    '',
  ].join('\n');
}

function renderRuntimeGuidanceSection(title: string, bullets: readonly string[]): string {
  return [
    `## ${title}`,
    '',
    ...bullets.map((line) => `- ${line}`),
    '',
  ].join('\n');
}

function renderContinuityContractSection(): string {
  return [
    `## ${CONTINUITY_CONTRACT_TITLE}`,
    '',
    ...CONTINUITY_CONTRACT_BULLETS.map((line) => `- ${line}`),
    '',
  ].join('\n');
}

// ---------------------------------------------------------------------------
// AGENTS.md template
// ---------------------------------------------------------------------------

const STOP_HOOK_SECTION = `## Stop-Hook (Optional)

If your runtime supports local stop hooks, configure \`agenticos-record-reminder\` as a local reminder. This is optional, not a canonical guardrail.`;

const RECORDING_PROTOCOL = `## MANDATORY: Recording Protocol

> All session activity MUST be recorded. If you skip this, context is lost forever.

**During session**: After completing any meaningful unit of work, call \`agenticos_record\` with summary, decisions, outcomes, pending, and current_task.

**Before session ends**: Call \`agenticos_record\` with complete summary, then \`agenticos_save\` to commit to Git.`;

export function generateAgentsMd(
  name: string,
  description: string,
  paths?: Partial<ManagedProjectContextDisplayPaths>,
): string {
  const contextPaths = normalizeAgentContextPaths(paths);

  const sessionStartProtocol = `## Session Start Protocol

On session start:

1. Call \`agenticos_status\` to confirm current project and task
2. If not on \`${name}\` project, call \`agenticos_switch\`
3. Read \`.project.yaml\`, \`${contextPaths.quickStartPath}\`, and \`${contextPaths.statePath}\`
4. If implementation work requested, enter Guardrail Protocol before editing
5. Greet with: project name, last progress, pending items, suggested next step`;

  return `${VERSION_MARKER}
# AGENTS.md — ${name}

## Adapter Role

${AGENTS_ADAPTER_LINES[0]}
${AGENTS_ADAPTER_LINES[1]}

${renderSharedPolicySection()}${renderRuntimeGuidanceSection(AGENTS_RUNTIME_GUIDANCE_TITLE, AGENTS_RUNTIME_GUIDANCE_BULLETS)}${STOP_HOOK_SECTION}

## ${TASK_INTAKE_RULE_TITLE}

${TASK_INTAKE_RULE_CONTENT}

## Guardrail Protocol (MANDATORY)

Before implementation edits, confirm session/project alignment with \`agenticos_status\`; if no session project is bound or the bound project is not the intended one, call \`agenticos_switch\`.

For implementation-affecting work:

1. call \`agenticos_preflight\`; if the result is \`REDIRECT\`, call \`agenticos_branch_bootstrap\` and continue in the returned worktree
2. after the issue worktree is active, perform the normal startup load and record \`agenticos_issue_bootstrap\`
3. rerun \`agenticos_preflight\` in that worktree before editing
4. call \`agenticos_edit_guard\` immediately before implementation edits
5. before PR creation or merge, call \`agenticos_pr_scope_check\`

If any guardrail command returns \`BLOCK\`, stop and resolve the blocking reason before continuing.

${RECORDING_PROTOCOL}

${sessionStartProtocol}
`;
}

// ---------------------------------------------------------------------------
// CLAUDE.md template
// ---------------------------------------------------------------------------

export function generateClaudeMd(
  name: string,
  description: string,
  // eslint-disable-next-line @typescript-eslint/no-explicit-any
  _state?: any,
  paths?: Partial<ManagedProjectContextDisplayPaths>,
): string {
  const contextPaths = normalizeAgentContextPaths(paths);

  return `${VERSION_MARKER}
# CLAUDE.md — ${name}

## Adapter Role

${CLAUDE_ADAPTER_LINES[0]}
${CLAUDE_ADAPTER_LINES[1]}

${renderSharedPolicySection()}${renderRuntimeGuidanceSection(CLAUDE_RUNTIME_GUIDANCE_TITLE, CLAUDE_RUNTIME_GUIDANCE_BULLETS)}${STOP_HOOK_SECTION}

## ${TASK_INTAKE_RULE_TITLE}

${TASK_INTAKE_RULE_CONTENT}

## Guardrail Protocol (MANDATORY)

Before implementation edits, confirm session/project alignment with \`agenticos_status\`; if no session project is bound or the bound project is not the intended one, call \`agenticos_switch\`.

For implementation-affecting work:

1. call \`agenticos_preflight\`; if the result is \`REDIRECT\`, call \`agenticos_branch_bootstrap\` and continue in the returned worktree
2. after the issue worktree is active, perform the normal startup load and record \`agenticos_issue_bootstrap\`
3. rerun \`agenticos_preflight\` in that worktree before editing
4. call \`agenticos_edit_guard\` immediately before implementation edits
5. before PR creation or merge, call \`agenticos_pr_scope_check\`

If any guardrail command returns \`BLOCK\`, stop and resolve the blocking reason before continuing.

${RECORDING_PROTOCOL}

## Session Start Protocol

On session start:

1. Call \`agenticos_status\` to confirm current project and task
2. If not on \`${name}\` project, call \`agenticos_switch\`
3. Read \`.project.yaml\`, \`${contextPaths.quickStartPath}\`, and \`${contextPaths.statePath}\`
4. If implementation work requested, enter Guardrail Protocol before editing
5. Greet with: project name, last progress, pending items, suggested next step
`;
}

/** @deprecated State is now in .context/state.yaml, not in CLAUDE.md */
export interface StateYaml {
  session?: { last_backup?: string };
  current_task?: { title?: string; status?: string } | null;
  working_memory?: { facts?: string[]; decisions?: string[]; pending?: string[] };
}

/** @deprecated Use generateClaudeMd instead. State is now in .context/state.yaml */
export function upgradeClaudeMd(
  _claudeMdPath: string,
  name: string,
  description: string,
  // eslint-disable-next-line @typescript-eslint/no-explicit-any
  _state?: any,
  paths?: Partial<ManagedProjectContextDisplayPaths>,
): string {
  return generateClaudeMd(name, description, undefined, paths);
}

/** @deprecated State is now in .context/state.yaml, not in CLAUDE.md */
export async function updateClaudeMdState(
  _claudeMdPath: string,
  _state: StateYaml,
  _projectName?: string,
  _projectDescription?: string,
): Promise<{ updated: boolean; created: boolean }> {
  // Since v14, state is kept in .context/state.yaml, not in CLAUDE.md
  return { updated: false, created: false };
}
